app:
  name: Oregami.org

spring:
  template:
    cache: false

logging:
  level:
    org.springframework.web:  DEBUG
    org.springframework.transaction:  DEBUG
    org.springframework.boot: DEBUG


